// <auto-generated />
namespace GestaoDDD.Infra.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class claims : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(claims));
        
        string IMigrationMetadata.Id
        {
            get { return "201512292041175_claims"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
